import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./component/navbar/page";
import FooterSection from "./component/footer/page";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "../context/AuthContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "NextShop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* AuthProvider দিয়ে整个 app কে wrap করুন */}
        <AuthProvider>
          <Navbar />
          <main>{children}</main>
          <Toaster />
          <FooterSection />
        </AuthProvider>
      </body>
    </html>
  );
}