import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


import { Toaster } from "react-hot-toast";
import NextAuthProvider from "@/Providers/NextAuthProvider";

import { ToastContainer } from "react-toastify";
import FooterSection from "../component/footer/footer";
import Navbar from "../component/navbar/Navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "NextShop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       
        <NextAuthProvider>
         <Navbar></Navbar>
          <main>{children}</main>
          <ToastContainer />
          <FooterSection />
        </NextAuthProvider>
      </body>
    </html>
  );
}